version: '3.8'
services:
  api:
    build:
      context: .
      args:
        - CREDENTIALS=${CREDENTIALS}
        - COOKIES=${COOKIES}
    command: poetry run uvicorn app.main.app:app --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  worker:
    build:
      context: .
      args:
        - CREDENTIALS=${CREDENTIALS}
        - COOKIES=${COOKIES}
    command: poetry run celery -A celery_worker.celery_app worker --loglevel=info -Q clipping
    depends_on:
      - redis-cont
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  redis-cont:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: redis-cont
